# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6091e63324fea6f28e351e153dc47a67229c3bdabd2190d31a00abf5b4f92c55266032cc076a092c46bf2779a98730163faff19c980976e30d94ad773943d411

test:
  secret_key_base: 25d44c8644fb6118b837c2bd64ea2bf8b354f701ebe2d0eb20c3da7cd08cc8912570c75d693c1d219a3cb8343d6eb45f0a1e1e9b7959710492ba0f8f576be62b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
